#ifndef PROTOCOL_H_
#define PROTOCOL_H_
#define MAVLINK_STX 253
#define MAVLINK_MAX_PAYLOAD_LEN 255
#define MAVLINK_NUM_HEADER_BYTES 9
#define MAVLINK_NUM_CHECKSUM_BYTES 2
#define MAVLINK_MAX_PACKET_LEN 280
#endif
